---
all:
  vars:
    ansible_host_key_checking: false
    ansible_ssh_timeout: 60
  hosts:
    demotest.local:
      ansible_host: 192.168.56.201
      ansible_user: vagrant
      ansible_ssh_private_key_file: ".vagrant/machines/demo/virtualbox/private_key"
