- name: Inv
  hosts: all
  become: true
  become_method: ansible.builtin.sudo

  tasks:
    - name: Set hostname
      # assumes 'inventory_hostname' is fqdn
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
        use: systemd

    - name: Set hostsfile
    # assumes a single interface
    # could also loop through ip's in 'ansible_all_ipv4_addresses'
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        regexp: "{{ hostvars[inventory_hostname]['ansible_facts'][ansible_default_ipv4.interface]['ipv4']['address'] }}"
        line: >
          {{ hostvars[inventory_hostname]['ansible_facts'][ansible_default_ipv4.interface]['ipv4']['address'] }}
          {{ inventory_hostname | split('.') | first }}
          {{ inventory_hostname }}
        state: present

    # - name: Set PS1
    #   ansible.builtin.lineinfile:
    #     dest: /etc/bashrc
    #     # regexp: '^\s+\[.+PS1=\"\[.*\\u@\\h \\W\]\\\\\$ \"'
    #     regexp: ^\s*[^\s^#].*S1=['"].*\\u@\\h.*$
    #     line: "    [ \"$PS1\" = \"\\s-\\v\\\\$ \" ] && PS1=\"[{{ inventory_hostname | split('.') | first }}-\\u@\\h \\W]\\$ \""

    - name: Set PS1
      ansible.builtin.copy:
        content: "PS1=\"[{{ inventory_hostname | split('.') | first }}-\\u@\\h \\W]\\$ \""
        dest: /etc/profile.d/ps1.sh
        mode: '0755'